### PR TITLE
example: add luarocks as build container

### PR DESCRIPTION
**Pull request by Tieske**
thx for the nice dockerfiles/images. I'm using them a lot as base images.

This example is something I have lying around and always keep copy-pasting from, hence I thought it might have a better place in this repo for others to use as well.

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Comment by akornatskyy** [comment]
there are probably better options, like: (a) github gist, (b) contribute to `copas` directly.

**Comment by Tieske** [comment]
I expected that comment.

The thing is that it is not specifically about Copas, but rather about which files to copy in general, when using the LuaRocks container as a build one. Which effectively is tied to this repo, since it uses those images.

**Comment by akornatskyy** [comment]
in your multi-stage example you build with `luarocks`... and in the final image you use `lua` as a base image and copy `luarocks` directory... that copy `luarocks` is confusing part for me. isn't the effect is the same as you would use just `luarocks` image?

in multi-stage build I eliminate build part all together (this is what I use [here](https://github.com/akornatskyy/scheduler/blob/master/misc/docker/Dockerfile))... but you pull it back.

**Comment by Tieske** [comment]
luarocks itself is part of the build tools. As such it shouldn't be in the final image, only the resulting libraries that it installed in the rockstrees.

So by using the `lua` image as the base I omit; these https://github.com/akornatskyy/docker-library/blob/master/luarocks/lua5.1/alpine/Dockerfile#L10-L12 and LuaRocks itself.

In my example I add these; https://github.com/akornatskyy/docker-library/pull/24/files#diff-a7f7442a856f23b00d9b8241f8ab271593b37d7bc6c442be6c1a7765d45d7f50R30-R32 but that is just for the example code. Maybe that is confusing, and this should be removed to make the example clearer.

**Comment by Tieske** [comment]
also; since the luarocks container to me pretty much is a build container, it might as well NOT remove these: https://github.com/akornatskyy/docker-library/blob/master/luarocks/lua5.1/alpine/Dockerfile#L29 since to use it as a build container pretty much means adding them again.

But that's just my common use case, not sure that works for everyone, or even what your initial goals were with the luarocks image.

**Comment by akornatskyy** [comment]
> In my example I add these; https://github.com/akornatskyy/docker-library/pull/24/files#diff-a7f7442a856f23b00d9b8241f8ab271593b37d7bc6c442be6c1a7765d45d7f50R30-R32 but that is just for the example code. Maybe that is confusing, and this should be removed to make the example clearer.

I would suggest add a comment that it is for runtime dependencies of respective modules added.

> also; since the luarocks container to me pretty much is a build container, it might as well NOT remove these: https://github.com/akornatskyy/docker-library/blob/master/luarocks/lua5.1/alpine/Dockerfile#L29 since to use it as a build container pretty much means adding them again.

In many cases `make`, `gcc` and `libc-dev` are build time dependencies, but not in all. I think it is better if you explicitly add them, instead of expecting them to be there already... as some packages might not need them.

**Comment by Tieske** [comment]
simplified the example by removing the LuaSec and OpenSSL dependency (they are optional for Copas anyway)

**Pull request merged**
